"""ztierfs：基于 SQLite 与内容寻址块的可写分层 FUSE 文件系统。

对外导出 `ZTierFS` 与常用默认常量（块大小、冷热层水位与内联阈值等），便于 `from ztierfs import ...`。
"""

from .constants import (
    CHUNK_SIZE,
    COMPRESSED_SUFFIXES,
    DEFAULT_COLD_COPY_CLEANUP_AGE_SECONDS,
    DEFAULT_HOT_CACHE_MAX_BYTES,
    DEFAULT_HOT_CACHE_MIN_BYTES,
    DEFAULT_INLINE_MAX_BYTES,
    DEFAULT_MIN_HOT_AGE_SECONDS,
    DEFAULT_PROTECTED_PREFIX_CHUNKS,
)
from .filesystem import ZTierFS

__all__ = [
    "CHUNK_SIZE",
    "COMPRESSED_SUFFIXES",
    "DEFAULT_COLD_COPY_CLEANUP_AGE_SECONDS",
    "DEFAULT_HOT_CACHE_MAX_BYTES",
    "DEFAULT_HOT_CACHE_MIN_BYTES",
    "DEFAULT_INLINE_MAX_BYTES",
    "DEFAULT_MIN_HOT_AGE_SECONDS",
    "DEFAULT_PROTECTED_PREFIX_CHUNKS",
    "ZTierFS",
]
